### ISSUE TITLE
How to use Librefox simultaneously with Firefox

### ISSUE THREAD

**Issue by brokoli-mate** [intika/Librefox#95] opened 2019-01-11 16:59 UTC
I would like to have separate profile in separate directory "librefox". 
When i first started librefox i was confusen because i ran into my firefox profile. So I have created new one and set it to use as default, but then I get firefox with the same profile and i am aware of firefox changing settings to less secure.
P. S. I know that there is a way to add the path of profile to exec command, but that is not what peaple expect when first run Librefox, IMO.

**Comment by intika** [comment] 2019-01-11 17:09
https://github.com/intika/Librefox/issues/55 once this will be done, the profile issue will be fixed,
also duplicate of https://github.com/intika/Librefox/issues/44

In the current situation if you want to separate Librefox from Firefox indeed you need to:
- Add a different profile for Firefox
- Make a copy of Firefox's install directory (to convert it to Librefox by applying the Librefox's config files)
- Create a new short cut (Librefox) to firefox/firefox.exe from the newly created/patched Firefox directory
- Set the shortcut to run the new profile you created for Librefox
`c:\...copied-patched-dir\core\firefox.exe -p librefox-profile -no-remote`

For further info check https://github.com/intika/Librefox/issues/44

**Closed by intika** 2019-01-11 17:09 UTC
Labels: duplicate, help wanted
